apiVersion: apps/v1
kind: Deployment
metadata:
  name: ex-frontend-deployment
  namespace: exam-shareebhashmi
spec:
  selector:
    matchLabels:
      app: ex-frontend-deployment
  template:
    metadata:
      labels:
        app: ex-frontend-deployment
    spec:
      containers:
      - name: ex-frontend-deployment
        image: nathansegers/containers_23-24_december_frontend:2.0
        resources: {}
        ports:
        - containerPort: 80  # Change this to match the port your application is listening on
---
apiVersion: v1
kind: Service
metadata:
  name: ex-frontend-service
spec:
  type: NodePort
  selector:
    app: ex-frontend-deployment
  ports:
  - port: 80        
    targetPort: 80 
    nodePort: 30000 

