apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: exam-shareebhashmi
  labels:
    createdBy: "Nathan-Segers"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api  
  template:
    metadata:
      labels:
        app: api
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: env
                operator: In
                values:
                - frontend
      containers:
        - image: nathansegers/containers_23-24_december_api
          imagePullPolicy: Always
          name: api-demo
          ports:
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - name: api-config
              mountPath: /config
          env:
            - name: ENV_NAME
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: ENV_NAME
            - name: DATA
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: DATA
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
      volumes:
        - name: api-config
          configMap:
            name: api-config

---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: NodePort
  selector:
    app: api
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30001
