version: "3.9"

services:
  web:
    build: ./pointsApp
    image: shareebhashmistudent/examen-nm:latest
    ports:
      - "5000:5000"
    networks:
      - web
    depends_on:
      - database
  database:
    image: postgres:16.1-alpine
    environment:
      - POSTGRES_DB=points
      - POSTGRES_USER=student
      - POSTGRES_PASSWORD=examen
    networks:
      - web
    volumes:
      - postgres:/var/lib/postgresql/data

networks:
  web:
  database:

volumes:
  postgres:
